# External service (NodePort)
# If you want to get the url of the service, you can use the following command: minikube service <service-name> --url
apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: NodePort # if running multiple pods, use a LoadBalancer type
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector: 
    name: voting-app-pod
    app: demo-voting-app