apiVersion: v1
kind: Pod # must be capital
metadata:
  name: myapp-pod
  labels:
    app: myapp
    tier: frontend
spec:
  containers:
  - name: nginx-container
    image: nginx 
    ports:
    - containerPort: 80
    command: ["echo", "hello"] 
    args: ["world"] 
    envFrom: # we use envFrom instead of env
    # secrets are not encrypted, they are just base64 encoded
    # do not check-in secrets to source control (SCM) with the code 
    # secrets are not ETCD encrypted by default 
      # go to kubernetes.io/docs/tasks/administer-cluster/encrypt-data for more info
      # https://www.youtube.com/watch?v=MTnQW9MxnRI
    # anyone able to create pods/deployments in the same namespace can access the secrets
      # 3rd party tools can be used to encrypt secrets to avoid handling administative tasks (AWS Provider, etc.)
    - secretRef:
        name: myapp-secret # name of the Secret (metadata.name)

# kubernetes defaults:
  # A secret is only sent to a node if a pod on that node requires it.
  # Kubelet stores the secret into a tmpfs so that the secret is not written to disk storage.
  # Once the Pod that depends on the secret is deleted, kubelet will delete its local copy of the secret data as well.