apiVersion: v1
kind: Pod # must be capital
metadata:
  name: myapp-pod
  labels:
    app: myapp
    tier: frontend
spec:
  containers:
  - name: nginx-container
    image: nginx # if not using dockerhub, use full path
    ports:
    - containerPort: 80
    command: ["echo", "hello"] 
    args: ["world"] 
    env: 
    - name: APP_NAME
      valueFrom:
        configMapKeyRef:
          name: app-config # name of the ConfigMap (metadata.name)
          key: APP_NAME # key in the ConfigMap