apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
data:
  # to encode a value to base64, use the following command:
  # echo -n 'value' | base64
  DB_HOST: bXlhcHA= # encoded value of mysql
  DB_USER: cm9vdA== # encoded value of root
  DB_PASS: cGFzd3Jk= # encoded value of paswrd

  # to decode a value from base64, use the following command:
  # echo -n 'bXlhcHA=' | base64 --decode

  # go to the pod to see notes on linking the secret to the pod